### ISSUE TITLE
Can't parse videos in the background.

### ISSUE THREAD

**Issue by fragm** [DaidoujiChen/DaiYoutubeParserSwift#1]
Can I use this framework in the background?
I tried but it didn't work.
I guess creating UIWebView in the background has some problems.

**Comment by DaidoujiChen** [comment]
Hello @fragm,

Do you mean use this tool in system `background mode` or just run on the other thread?

If you want to run this tool in `background mode` I think it may possible.

If you want to run this tool in other thread it will fail by `UIWebView` limitation.

thanks.

**Comment by fragm** [comment]
Thanks for your reply.
Maybe I want to run this tool in system background mode (after applicationDidEnterBackground).

I want to parse a new video url after finish playing a video in the background mode.
It's possible in the foreground.
But if I call a method (DaiYoutubeParser.parse) in the background mode, can't get a url & a video title.

**Comment by DaidoujiChen** [comment]
Hello @fragm,

Let me try on tomorrow. THX.

**Comment by fragm** [comment]
Thanks.
Of course, that's okay.

**Comment by DaidoujiChen** [comment]
Hello @fragm,

After Tested.
This tool can't run in background mode. The reason maybe

```
You only have 10 or so seconds to resume your app. 
Your app is apparently doing too much work on the main thread, 
something that takes longer than 10 seconds, 
and therefore the watchdog timer kills your app.
```

[Reference Here](http://www.raywenderlich.com/forums/viewtopic.php?f=2&t=4591)

UIWebView keep main thread too much time.

**Comment by fragm** [comment]
Thanks. I got it.
If you find a solution, please update.

**Comment by DaidoujiChen** [comment]
:+1:
